// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Robert Harris

import * as math from 'mathjs';

export interface RewriteRule {
  id: string;
  name: string;
  category: string;
  sourcePatternStr: string;
  targetPatternStr: string;
  sourcePattern: math.MathNode;
  targetPattern: math.MathNode;
  description: string;
}

interface RawRule {
  id: string;
  name: string;
  category: string;
  sourcePatternStr: string;
  targetPatternStr: string;
  description: string;
}

const RAW_RULES: RawRule[] = [
  // 1. Polynomial & Factoring Identities
  {
    id: 'diff_squares_factor',
    name: 'Factor Difference of Squares',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '_A^2 - _B^2',
    targetPatternStr: '(_A - _B) * (_A + _B)',
    description: 'Factors the difference of two squared terms.',
  },
  {
    id: 'diff_squares_expand',
    name: 'Expand Conjugate Binomials',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '(_A - _B) * (_A + _B)',
    targetPatternStr: '_A^2 - _B^2',
    description: 'Expands conjugate factors into a difference of squares.',
  },
  {
    id: 'perfect_square_factor_plus',
    name: 'Factor Perfect Square (Sum)',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '_A^2 + 2 * _A * _B + _B^2',
    targetPatternStr: '(_A + _B)^2',
    description: 'Factors a trinomial of the form a^2 + 2ab + b^2 into a squared sum.',
  },
  {
    id: 'perfect_square_factor_minus',
    name: 'Factor Perfect Square (Difference)',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '_A^2 - 2 * _A * _B + _B^2',
    targetPatternStr: '(_A - _B)^2',
    description: 'Factors a trinomial of the form a^2 - 2ab + b^2 into a squared difference.',
  },
  {
    id: 'diff_cubes_factor',
    name: 'Factor Difference of Cubes',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '_A^3 - _B^3',
    targetPatternStr: '(_A - _B) * (_A^2 + _A * _B + _B^2)',
    description: 'Factors a^3 - b^3 into (a - b)(a^2 + ab + b^2).',
  },
  {
    id: 'sum_cubes_factor',
    name: 'Factor Sum of Cubes',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '_A^3 + _B^3',
    targetPatternStr: '(_A + _B) * (_A^2 - _A * _B + _B^2)',
    description: 'Factors a^3 + b^3 into (a + b)(a^2 - ab + b^2).',
  },
  {
    id: 'perfect_square_expand_plus',
    name: 'Expand Binomial Square (Sum)',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '(_A + _B)^2',
    targetPatternStr: '_A^2 + 2 * _A * _B + _B^2',
    description: 'Expands a squared sum binomial into trinomial form.',
  },
  {
    id: 'perfect_square_expand_minus',
    name: 'Expand Binomial Square (Difference)',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '(_A - _B)^2',
    targetPatternStr: '_A^2 - 2 * _A * _B + _B^2',
    description: 'Expands a squared difference binomial into trinomial form.',
  },
  {
    id: 'sum_cubes_factor',
    name: 'Factor Sum of Cubes',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '_A^3 + _B^3',
    targetPatternStr: '(_A + _B) * (_A^2 - _A * _B + _B^2)',
    description: 'Factors the sum of two cubed terms.',
  },
  {
    id: 'diff_cubes_factor',
    name: 'Factor Difference of Cubes',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '_A^3 - _B^3',
    targetPatternStr: '(_A - _B) * (_A^2 + _A * _B + _B^2)',
    description: 'Factors the difference of two cubed terms.',
  },
  {
    id: 'sum_cubes_expand',
    name: 'Expand Sum of Cubes Factors',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '(_A + _B) * (_A^2 - _A * _B + _B^2)',
    targetPatternStr: '_A^3 + _B^3',
    description: 'Expands factored sum of cubes back to polynomial sum.',
  },
  {
    id: 'diff_cubes_expand',
    name: 'Expand Difference of Cubes Factors',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '(_A - _B) * (_A^2 + _A * _B + _B^2)',
    targetPatternStr: '_A^3 - _B^3',
    description: 'Expands factored difference of cubes back to polynomial difference.',
  },
  {
    id: 'cube_sum_factor',
    name: 'Factor Perfect Cube (Sum)',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '_A^3 + 3 * _A^2 * _B + 3 * _A * _B^2 + _B^3',
    targetPatternStr: '(_A + _B)^3',
    description: 'Factors a perfect quadrinomial of the form a^3 + 3a^2b + 3ab^2 + b^3 into a cubed sum.',
  },
  {
    id: 'cube_sum_expand',
    name: 'Expand Binomial Cube (Sum)',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '(_A + _B)^3',
    targetPatternStr: '_A^3 + 3 * _A^2 * _B + 3 * _A * _B^2 + _B^3',
    description: 'Expands a cubed sum binomial into its expanded polynomial form.',
  },
  {
    id: 'cube_diff_factor',
    name: 'Factor Perfect Cube (Difference)',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '_A^3 - 3 * _A^2 * _B + 3 * _A * _B^2 - _B^3',
    targetPatternStr: '(_A - _B)^3',
    description: 'Factors a perfect quadrinomial of the form a^3 - 3a^2b + 3ab^2 - b^3 into a cubed difference.',
  },
  {
    id: 'cube_diff_expand',
    name: 'Expand Binomial Cube (Difference)',
    category: 'Polynomials & Factoring',
    sourcePatternStr: '(_A - _B)^3',
    targetPatternStr: '_A^3 - 3 * _A^2 * _B + 3 * _A * _B^2 - _B^3',
    description: 'Expands a cubed difference binomial into its expanded polynomial form.',
  },
  // 2. Exponent Rules
  {
    id: 'exponent_product',
    name: 'Product of Powers',
    category: 'Exponent Rules',
    sourcePatternStr: '_x^_A * _x^_B',
    targetPatternStr: '_x^(_A + _B)',
    description: 'Combines multiplication of powers sharing the same base.',
  },
  {
    id: 'exponent_product_reverse',
    name: 'Product of Powers (Reverse)',
    category: 'Exponent Rules',
    sourcePatternStr: '_x^(_A + _B)',
    targetPatternStr: '_x^_A * _x^_B',
    description: 'Splits a summed exponent into a product of powers.',
  },
  {
    id: 'exponent_quotient',
    name: 'Quotient of Powers',
    category: 'Exponent Rules',
    sourcePatternStr: '_x^_A / _x^_B',
    targetPatternStr: '_x^(_A - _B)',
    description: 'Simplifies division of powers sharing the same base.',
  },
  {
    id: 'exponent_quotient_reverse',
    name: 'Quotient of Powers (Reverse)',
    category: 'Exponent Rules',
    sourcePatternStr: '_x^(_A - _B)',
    targetPatternStr: '_x^_A / _x^_B',
    description: 'Splits a subtracted exponent into a division of powers.',
  },
  {
    id: 'exponent_power_of_power',
    name: 'Power of a Power',
    category: 'Exponent Rules',
    sourcePatternStr: '(_x^_A)^_B',
    targetPatternStr: '_x^(_A * _B)',
    description: 'Simplifies a power raised to another exponent.',
  },
  {
    id: 'exponent_power_of_power_reverse',
    name: 'Power of a Power (Reverse)',
    category: 'Exponent Rules',
    sourcePatternStr: '_x^(_A * _B)',
    targetPatternStr: '(_x^_A)^_B',
    description: 'Splits a multiplied exponent into a power raised to an exponent.',
  },
  {
    id: 'exponent_power_of_product',
    name: 'Power of a Product',
    category: 'Exponent Rules',
    sourcePatternStr: '(_x * _y)^_A',
    targetPatternStr: '_x^_A * _y^_A',
    description: 'Distributes the exponent to terms inside a product.',
  },
  {
    id: 'exponent_power_of_product_reverse',
    name: 'Factor Exponent Out of Product',
    category: 'Exponent Rules',
    sourcePatternStr: '_x^_A * _y^_A',
    targetPatternStr: '(_x * _y)^_A',
    description: 'Factors a common exponent out of multiplied power terms.',
  },
  {
    id: 'exponent_power_of_quotient',
    name: 'Power of a Quotient',
    category: 'Exponent Rules',
    sourcePatternStr: '(_x / _y)^_A',
    targetPatternStr: '_x^_A / _y^_A',
    description: 'Distributes the exponent to numerator and denominator.',
  },
  {
    id: 'exponent_power_of_quotient_reverse',
    name: 'Factor Exponent Out of Quotient',
    category: 'Exponent Rules',
    sourcePatternStr: '_x^_A / _y^_A',
    targetPatternStr: '(_x / _y)^_A',
    description: 'Factors a common exponent out of divided power terms.',
  },
  {
    id: 'exponent_negative',
    name: 'Negative Exponent Rule',
    category: 'Exponent Rules',
    sourcePatternStr: '_x^-_A',
    targetPatternStr: '1 / _x^_A',
    description: 'Expresses negative powers as reciprocals.',
  },
  {
    id: 'exponent_negative_reverse',
    name: 'Negative Exponent Rule (Reverse)',
    category: 'Exponent Rules',
    sourcePatternStr: '1 / _x^_A',
    targetPatternStr: '_x^-_A',
    description: 'Expresses fraction powers as negative exponents.',
  },
  {
    id: 'exponent_sqrt',
    name: 'Square Root to Fractional Power',
    category: 'Exponent Rules',
    sourcePatternStr: 'sqrt(_x)',
    targetPatternStr: '_x^(1 / 2)',
    description: 'Converts a square root to an exponent of 1/2.',
  },
  {
    id: 'exponent_sqrt_reverse',
    name: 'Fractional Power to Square Root',
    category: 'Exponent Rules',
    sourcePatternStr: '_x^(1 / 2)',
    targetPatternStr: 'sqrt(_x)',
    description: 'Converts a power of 1/2 to a square root.',
  },
  {
    id: 'exponent_nthRoot',
    name: 'Nth Root to Fractional Power',
    category: 'Exponent Rules',
    sourcePatternStr: 'nthRoot(_x, _n)',
    targetPatternStr: '_x^(1 / _n)',
    description: 'Converts an nth root to a fractional exponent 1/n.',
  },
  {
    id: 'exponent_nthRoot_reverse',
    name: 'Fractional Power to Nth Root',
    category: 'Exponent Rules',
    sourcePatternStr: '_x^(1 / _n)',
    targetPatternStr: 'nthRoot(_x, _n)',
    description: 'Converts a fractional exponent 1/n to an nth root.',
  },

  // 3. Logarithm Rules
  {
    id: 'log_product',
    name: 'Logarithm Product Rule',
    category: 'Logarithm Rules',
    sourcePatternStr: 'log(_A * _B)',
    targetPatternStr: 'log(_A) + log(_B)',
    description: 'Expands the logarithm of a product into a sum of logarithms.',
  },
  {
    id: 'log_quotient',
    name: 'Logarithm Quotient Rule',
    category: 'Logarithm Rules',
    sourcePatternStr: 'log(_A / _B)',
    targetPatternStr: 'log(_A) - log(_B)',
    description: 'Expands the logarithm of a quotient into a difference of logarithms.',
  },
  {
    id: 'log_power',
    name: 'Logarithm Power Rule',
    category: 'Logarithm Rules',
    sourcePatternStr: 'log(_A^_k)',
    targetPatternStr: '_k * log(_A)',
    description: 'Moves the exponent inside a logarithm to a multiplier coefficient.',
  },
  {
    id: 'log_product_reverse',
    name: 'Logarithm Product Rule (Reverse)',
    category: 'Logarithm Rules',
    sourcePatternStr: 'log(_A) + log(_B)',
    targetPatternStr: 'log(_A * _B)',
    description: 'Condenses the sum of two logarithms into the logarithm of their product.',
  },
  {
    id: 'log_quotient_reverse',
    name: 'Logarithm Quotient Rule (Reverse)',
    category: 'Logarithm Rules',
    sourcePatternStr: 'log(_A) - log(_B)',
    targetPatternStr: 'log(_A / _B)',
    description: 'Condenses the difference of two logarithms into the logarithm of their quotient.',
  },
  {
    id: 'log_power_reverse',
    name: 'Logarithm Power Rule (Reverse)',
    category: 'Logarithm Rules',
    sourcePatternStr: '_k * log(_A)',
    targetPatternStr: 'log(_A^_k)',
    description: 'Moves a multiplier coefficient outside a logarithm to the exponent of the argument.',
  },
  {
    id: 'log_change_base',
    name: 'Logarithm Change of Base',
    category: 'Logarithm Rules',
    sourcePatternStr: 'log(_A, _base)',
    targetPatternStr: 'log(_A) / log(_base)',
    description: 'Rewrites a logarithm with any base using natural logarithms.',
  },
  {
    id: 'log_change_base_reverse',
    name: 'Logarithm Change of Base (Reverse)',
    category: 'Logarithm Rules',
    sourcePatternStr: 'log(_A) / log(_base)',
    targetPatternStr: 'log(_A, _base)',
    description: 'Condenses a quotient of natural logarithms into a single logarithm with a custom base.',
  },

  // 4. Trigonometric Identities
  {
    id: 'trig_pythagorean',
    name: 'Pythagorean Identity',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'sin(_theta)^2 + cos(_theta)^2',
    targetPatternStr: '1',
    description: 'Simplifies sin^2 + cos^2 of any angle to 1.',
  },
  {
    id: 'trig_tan_def',
    name: 'Tangent Quotient Identity',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'tan(_theta)',
    targetPatternStr: 'sin(_theta) / cos(_theta)',
    description: 'Expresses tangent as sine divided by cosine.',
  },
  {
    id: 'trig_tan_def_reverse',
    name: 'Tangent Quotient Identity (Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'sin(_theta) / cos(_theta)',
    targetPatternStr: 'tan(_theta)',
    description: 'Rewrites sin/cos quotient as tangent.',
  },
  {
    id: 'trig_sec_def',
    name: 'Secant Reciprocal Identity',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'sec(_theta)',
    targetPatternStr: '1 / cos(_theta)',
    description: 'Expresses secant as the reciprocal of cosine.',
  },
  {
    id: 'trig_sec_def_reverse',
    name: 'Secant Reciprocal Identity (Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: '1 / cos(_theta)',
    targetPatternStr: 'sec(_theta)',
    description: 'Rewrites reciprocal of cosine as secant.',
  },
  {
    id: 'trig_csc_def',
    name: 'Cosecant Reciprocal Identity',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'csc(_theta)',
    targetPatternStr: '1 / sin(_theta)',
    description: 'Expresses cosecant as the reciprocal of sine.',
  },
  {
    id: 'trig_csc_def_reverse',
    name: 'Cosecant Reciprocal Identity (Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: '1 / sin(_theta)',
    targetPatternStr: 'csc(_theta)',
    description: 'Rewrites reciprocal of sine as cosecant.',
  },
  {
    id: 'trig_double_sin',
    name: 'Double Angle Sine',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'sin(2 * _theta)',
    targetPatternStr: '2 * sin(_theta) * cos(_theta)',
    description: 'Expands sine of a double angle.',
  },
  {
    id: 'trig_double_sin_reverse',
    name: 'Double Angle Sine (Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: '2 * sin(_theta) * cos(_theta)',
    targetPatternStr: 'sin(2 * _theta)',
    description: 'Condenses double angle sine product.',
  },
  {
    id: 'trig_cot_def',
    name: 'Cotangent Quotient Identity',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'cot(_theta)',
    targetPatternStr: 'cos(_theta) / sin(_theta)',
    description: 'Expresses cotangent as cosine divided by sine.',
  },
  {
    id: 'trig_cot_def_reverse',
    name: 'Cotangent Quotient Identity (Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'cos(_theta) / sin(_theta)',
    targetPatternStr: 'cot(_theta)',
    description: 'Rewrites cos/sin quotient as cotangent.',
  },
  {
    id: 'trig_cot_reciprocal',
    name: 'Cotangent Reciprocal Identity',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'cot(_theta)',
    targetPatternStr: '1 / tan(_theta)',
    description: 'Expresses cotangent as the reciprocal of tangent.',
  },
  {
    id: 'trig_cot_reciprocal_reverse',
    name: 'Cotangent Reciprocal Identity (Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: '1 / tan(_theta)',
    targetPatternStr: 'cot(_theta)',
    description: 'Rewrites reciprocal of tangent as cotangent.',
  },
  {
    id: 'trig_tan_reciprocal',
    name: 'Tangent Reciprocal Identity',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'tan(_theta)',
    targetPatternStr: '1 / cot(_theta)',
    description: 'Expresses tangent as the reciprocal of cotangent.',
  },
  {
    id: 'trig_tan_reciprocal_reverse',
    name: 'Tangent Reciprocal Identity (Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: '1 / cot(_theta)',
    targetPatternStr: 'tan(_theta)',
    description: 'Rewrites reciprocal of cotangent as tangent.',
  },
  {
    id: 'trig_pythagorean_cos_sq',
    name: 'Pythagorean Identity (cos^2)',
    category: 'Trigonometric Identities',
    sourcePatternStr: '1 - sin(_theta)^2',
    targetPatternStr: 'cos(_theta)^2',
    description: 'Rewrites 1 - sin^2 as cos^2.',
  },
  {
    id: 'trig_pythagorean_cos_sq_reverse',
    name: 'Pythagorean Identity (cos^2, Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'cos(_theta)^2',
    targetPatternStr: '1 - sin(_theta)^2',
    description: 'Rewrites cos^2 as 1 - sin^2.',
  },
  {
    id: 'trig_pythagorean_sin_sq',
    name: 'Pythagorean Identity (sin^2)',
    category: 'Trigonometric Identities',
    sourcePatternStr: '1 - cos(_theta)^2',
    targetPatternStr: 'sin(_theta)^2',
    description: 'Rewrites 1 - cos^2 as sin^2.',
  },
  {
    id: 'trig_pythagorean_sin_sq_reverse',
    name: 'Pythagorean Identity (sin^2, Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'sin(_theta)^2',
    targetPatternStr: '1 - cos(_theta)^2',
    description: 'Rewrites sin^2 as 1 - cos^2.',
  },
  {
    id: 'trig_pythagorean_tan_sec',
    name: 'Pythagorean Identity (tan/sec)',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'tan(_theta)^2 + 1',
    targetPatternStr: 'sec(_theta)^2',
    description: 'Rewrites tan^2 + 1 as sec^2.',
  },
  {
    id: 'trig_pythagorean_tan_sec_reverse',
    name: 'Pythagorean Identity (tan/sec, Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'sec(_theta)^2 - 1',
    targetPatternStr: 'tan(_theta)^2',
    description: 'Rewrites sec^2 - 1 as tan^2.',
  },
  {
    id: 'trig_pythagorean_cot_csc',
    name: 'Pythagorean Identity (cot/csc)',
    category: 'Trigonometric Identities',
    sourcePatternStr: '1 + cot(_theta)^2',
    targetPatternStr: 'csc(_theta)^2',
    description: 'Rewrites 1 + cot^2 as csc^2.',
  },
  {
    id: 'trig_pythagorean_cot_csc_reverse',
    name: 'Pythagorean Identity (cot/csc, Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'csc(_theta)^2 - 1',
    targetPatternStr: 'cot(_theta)^2',
    description: 'Rewrites csc^2 - 1 as cot^2.',
  },
  {
    id: 'trig_double_cos_form1',
    name: 'Double Angle Cosine (cos^2 - sin^2)',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'cos(2 * _theta)',
    targetPatternStr: 'cos(_theta)^2 - sin(_theta)^2',
    description: 'Expands cosine of a double angle into difference of squares.',
  },
  {
    id: 'trig_double_cos_form1_reverse',
    name: 'Double Angle Cosine (cos^2 - sin^2, Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'cos(_theta)^2 - sin(_theta)^2',
    targetPatternStr: 'cos(2 * _theta)',
    description: 'Condenses difference of squared trig terms into double angle cosine.',
  },
  {
    id: 'trig_double_cos_form2',
    name: 'Double Angle Cosine (2cos^2 - 1)',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'cos(2 * _theta)',
    targetPatternStr: '2 * cos(_theta)^2 - 1',
    description: 'Expands cosine of a double angle using cosine only.',
  },
  {
    id: 'trig_double_cos_form2_reverse',
    name: 'Double Angle Cosine (2cos^2 - 1, Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: '2 * cos(_theta)^2 - 1',
    targetPatternStr: 'cos(2 * _theta)',
    description: 'Condenses cosine term into double angle cosine.',
  },
  {
    id: 'trig_double_cos_form3',
    name: 'Double Angle Cosine (1 - 2sin^2)',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'cos(2 * _theta)',
    targetPatternStr: '1 - 2 * sin(_theta)^2',
    description: 'Expands cosine of a double angle using sine only.',
  },
  {
    id: 'trig_double_cos_form3_reverse',
    name: 'Double Angle Cosine (1 - 2sin^2, Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: '1 - 2 * sin(_theta)^2',
    targetPatternStr: 'cos(2 * _theta)',
    description: 'Condenses sine term into double angle cosine.',
  },
  {
    id: 'trig_double_tan',
    name: 'Double Angle Tangent',
    category: 'Trigonometric Identities',
    sourcePatternStr: 'tan(2 * _theta)',
    targetPatternStr: '(2 * tan(_theta)) / (1 - tan(_theta)^2)',
    description: 'Expands tangent of a double angle.',
  },
  {
    id: 'trig_double_tan_reverse',
    name: 'Double Angle Tangent (Reverse)',
    category: 'Trigonometric Identities',
    sourcePatternStr: '(2 * tan(_theta)) / (1 - tan(_theta)^2)',
    targetPatternStr: 'tan(2 * _theta)',
    description: 'Condenses tangent expression into double angle tangent.',
  },
  {
    id: 'repeated_addition_2',
    name: 'Express as Repeated Addition',
    category: 'Basic Arithmetic',
    sourcePatternStr: '2 * _A',
    targetPatternStr: '_A + _A',
    description: 'Converts multiplication by 2 into repeated addition of the term.',
  },
  {
    id: 'repeated_addition_2_right',
    name: 'Express as Repeated Addition',
    category: 'Basic Arithmetic',
    sourcePatternStr: '_A * 2',
    targetPatternStr: '_A + _A',
    description: 'Converts multiplication by 2 into repeated addition of the term.',
  },
  {
    id: 'repeated_addition_2_reverse',
    name: 'Express as Multiplication',
    category: 'Basic Arithmetic',
    sourcePatternStr: '_A + _A',
    targetPatternStr: '2 * _A',
    description: 'Combines two identical terms into multiplication by 2.',
  },
  {
    id: 'repeated_addition_3',
    name: 'Express as Repeated Addition',
    category: 'Basic Arithmetic',
    sourcePatternStr: '3 * _A',
    targetPatternStr: '_A + _A + _A',
    description: 'Converts multiplication by 3 into repeated addition of the term.',
  },
  {
    id: 'repeated_addition_3_right',
    name: 'Express as Repeated Addition',
    category: 'Basic Arithmetic',
    sourcePatternStr: '_A * 3',
    targetPatternStr: '_A + _A + _A',
    description: 'Converts multiplication by 3 into repeated addition of the term.',
  },
  {
    id: 'repeated_addition_3_reverse',
    name: 'Express as Multiplication',
    category: 'Basic Arithmetic',
    sourcePatternStr: '_A + _A + _A',
    targetPatternStr: '3 * _A',
    description: 'Combines three identical terms into multiplication by 3.',
  },
  {
    id: 'repeated_addition_4',
    name: 'Express as Repeated Addition',
    category: 'Basic Arithmetic',
    sourcePatternStr: '4 * _A',
    targetPatternStr: '_A + _A + _A + _A',
    description: 'Converts multiplication by 4 into repeated addition of the term.',
  },
  {
    id: 'repeated_addition_4_right',
    name: 'Express as Repeated Addition',
    category: 'Basic Arithmetic',
    sourcePatternStr: '_A * 4',
    targetPatternStr: '_A + _A + _A + _A',
    description: 'Converts multiplication by 4 into repeated addition of the term.',
  },
  {
    id: 'repeated_addition_4_reverse',
    name: 'Express as Multiplication',
    category: 'Basic Arithmetic',
    sourcePatternStr: '_A + _A + _A + _A',
    targetPatternStr: '4 * _A',
    description: 'Combines four identical terms into multiplication by 4.',
  },
  {
    id: 'repeated_addition_5',
    name: 'Express as Repeated Addition',
    category: 'Basic Arithmetic',
    sourcePatternStr: '5 * _A',
    targetPatternStr: '_A + _A + _A + _A + _A',
    description: 'Converts multiplication by 5 into repeated addition of the term.',
  },
  {
    id: 'repeated_addition_5_right',
    name: 'Express as Repeated Addition',
    category: 'Basic Arithmetic',
    sourcePatternStr: '_A * 5',
    targetPatternStr: '_A + _A + _A + _A + _A',
    description: 'Converts multiplication by 5 into repeated addition of the term.',
  },
  {
    id: 'repeated_addition_5_reverse',
    name: 'Express as Multiplication',
    category: 'Basic Arithmetic',
    sourcePatternStr: '_A + _A + _A + _A + _A',
    targetPatternStr: '5 * _A',
    description: 'Combines five identical terms into multiplication by 5.',
  },
  {
    id: 'fraction_decompose',
    name: 'Decompose Fraction',
    category: 'Basic Arithmetic',
    sourcePatternStr: '_A / _B',
    targetPatternStr: '_A * (1 / _B)',
    description: 'Decomposes a division into multiplication by a reciprocal.',
  },
  {
    id: 'fraction_compose',
    name: 'Decompose Fraction (Reverse)',
    category: 'Basic Arithmetic',
    sourcePatternStr: '_A * (1 / _B)',
    targetPatternStr: '_A / _B',
    description: 'Combines multiplication by a reciprocal into a division.',
  },
];

export const HIGH_SCHOOL_IDENTITIES: RewriteRule[] = RAW_RULES.map((rule) => {
  try {
    return {
      ...rule,
      sourcePattern: math.parse(rule.sourcePatternStr),
      targetPattern: math.parse(rule.targetPatternStr),
    };
  } catch (err) {
    console.error(`Failed to parse rewrite rule patterns for: ${rule.id}`, err);
    throw err;
  }
});
