// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Robert Harris

import { describe, it, expect, beforeAll, afterAll, beforeEach, afterEach, vi } from 'vitest';
import { Blob as NodeBlob } from 'node:buffer';
import { parseEquation, decompressString } from 'math-engine-client';

// jsdom's Blob lacks `.stream()`, which the engine's gzip-based share
// (de)compression relies on. Swap in Node's Blob (with CompressionStream, a
// Node 18+ global) for this file so the real share path runs unmodified.
let originalBlob: typeof globalThis.Blob;
beforeAll(() => {
  originalBlob = globalThis.Blob;
  globalThis.Blob = NodeBlob as unknown as typeof globalThis.Blob;
});
afterAll(() => {
  globalThis.Blob = originalBlob;
});
import {
  serializeWorkspaceState,
  deminifyWorkspace,
  type HistoryNode,
} from '@/store/equation';
import { buildWorkspaceUrl, buildEquationUrl } from '@/utils/feedbackUrl';
import { safeStorage } from '@/utils/safeStorage';

/**
 * #326 core-flow guarantee: with JS storage fully blocked (a privacy extension
 * denying localStorage), the user can still type an equation, build a small
 * derivation tree, and share it via URL. The share path uses URL/compression,
 * never storage — this locks that in so a future storage coupling can't regress it.
 */

const ORIGIN = 'https://algebranch.org';

function blockStorage(): () => void {
  const original = Object.getOwnPropertyDescriptor(window, 'localStorage');
  Object.defineProperty(window, 'localStorage', {
    configurable: true,
    get() {
      throw new DOMException('denied', 'SecurityError');
    },
  });
  return () => {
    if (original) Object.defineProperty(window, 'localStorage', original);
  };
}

let restore: () => void;

beforeEach(() => {
  vi.spyOn(console, 'warn').mockImplementation(() => {});
  restore = blockStorage();
});

afterEach(() => {
  restore();
  vi.restoreAllMocks();
});

describe('core flow with storage blocked', () => {
  it('persistence attempts never throw out to the app', () => {
    expect(() => {
      safeStorage.setItem('algebranch_history_tree', '{"0":{}}');
      safeStorage.getItem('algebranch_history_tree');
    }).not.toThrow();
  });

  it('shares a worked derivation via a ?ws= URL that round-trips', async () => {
    // Type an equation and take one step → a two-node history tree.
    const tree: Record<string, HistoryNode> = {
      '0': {
        id: '0',
        equation: parseEquation('2*(x+3)=10'),
        parentId: null,
        childrenIds: ['1'],
        label: 'Initial',
        timestamp: 1,
      },
      '1': {
        id: '1',
        equation: parseEquation('2*x+6=10'),
        parentId: '0',
        childrenIds: [],
        label: 'Distribute',
        timestamp: 2,
      },
    };

    const compressed = await serializeWorkspaceState(tree, '1', 'My work');
    expect(compressed).toBeTruthy();

    const url = buildWorkspaceUrl(ORIGIN, compressed);
    expect(url).toContain('/?ws=');

    // Recipient side: the link decompresses and deminifies back to the state.
    // (Node IDs are regenerated by deminify, so assert structure, not literal ids.)
    const param = url.split('?ws=')[1];
    const restored = deminifyWorkspace(JSON.parse(await decompressString(param)));
    expect(restored.name).toBe('My work');
    expect(Object.keys(restored.tree)).toHaveLength(2);
    // The shared "current" node survives the round-trip and is in the tree.
    expect(restored.tree[restored.currentNodeId]).toBeDefined();
  });

  it('shares a single equation via a ?eq= URL', () => {
    const url = buildEquationUrl(ORIGIN, '2*(x+3)=10');
    expect(url).toContain('/?eq=');
    // The encoded equation survives the round-trip back to the original string.
    const decoded = decodeURIComponent(url.split('?eq=')[1]);
    expect(decoded).toBe('2*(x+3)=10');
  });
});
