// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Robert Harris

export interface Preset {
  id: string;
  slug: string;
  label: string;
  equation: string;
  description: string;
  category: 'Practice Problems' | 'Formulas & Laws' | 'Algebraic Identities';
  subcategory: string;
  type: 'solvable' | 'formula' | 'identity';
  wikiUrl?: string;
  tags?: string[];
  /**
   * Optional capability gates required for this preset.
   * Uses three-state logic (Must be True, Must be False, Don't Care):
   * - true: The capability MUST be enabled in the workspace.
   * - false: The capability MUST be disabled in the workspace.
   * - undefined / omitted: "Don't Care" (the preset does not impose any requirement).
   */
  requiredSettings?: {
    allowComplex?: boolean;
    allowEvaluateToDecimal?: boolean;
  };
}

export const PRESET_LIST: Preset[] = [
  {
    id: 'linear_basic',
    slug: 'linear-basic',
    label: 'Basic Linear Equation',
    equation: '2 * x + 4 = 10',
    description: "Basic 2-step linear equation.\n\n- **x**: target variable\n- **2**: variable coefficient\n- **4, 10**: constant terms",
    category: 'Practice Problems',
    subcategory: 'Linear',
    type: 'solvable',
  },
  {
    id: 'linear_both_sides',
    slug: 'linear-both-sides',
    label: 'Variables on Both Sides',
    equation: '3 * x + 5 = x + 13',
    description: "Linear equation with variable terms on LHS and RHS.\n\n- **x**: target variable\n- **3, 1**: coefficients\n- **5, 13**: constants",
    category: 'Practice Problems',
    subcategory: 'Linear',
    type: 'solvable',
  },
  {
    id: 'linear_negative',
    slug: 'linear-negative',
    label: 'Negative Coefficients',
    equation: '-2 * x + 7 = 15',
    description: "Linear equation with a negative coefficient.\n\n- **x**: target variable\n- **-2**: negative coefficient\n- **7, 15**: constants",
    category: 'Practice Problems',
    subcategory: 'Linear',
    type: 'solvable',
  },
  {
    id: 'linear_distribution',
    slug: 'linear-distribution',
    label: 'Distribution Form',
    equation: '3 * (x - 2) = 18',
    description: "Linear equation requiring distributive expansion.\n\n- **x**: target variable\n- **3**: multiplier factor\n- **2, 18**: constants",
    category: 'Practice Problems',
    subcategory: 'Linear',
    type: 'solvable',
  },
  {
    id: 'linear_multi_step',
    slug: 'linear-multi-step',
    label: 'Multi-Step Linear',
    equation: '5 * x - 3 + 2 * x = 4 * x + 9',
    description: "Multi-step equation requiring like-term combination.\n\n- **x**: target variable\n- **5, 2, 4**: variable coefficients",
    category: 'Practice Problems',
    subcategory: 'Linear',
    type: 'solvable',
  },
  {
    id: 'quadratic_basic_solve',
    slug: 'quadratic-basic-solve',
    label: 'Pure Quadratic Equation',
    equation: 'x^2 - 9 = 0',
    description: "Pure quadratic equation solvable via square root extraction.\n\n- **x**: target variable\n- **9**: constant term",
    category: 'Practice Problems',
    subcategory: 'Quadratic',
    type: 'solvable',
  },
  {
    id: 'quadratic_factor_monic',
    slug: 'quadratic-factor-monic',
    label: 'Factor Monic Quadratic',
    equation: 'x^2 + 5 * x + 6 = 0',
    description: "Monic quadratic polynomial solvable by factoring into (x + a)(x + b).\n\n- **x**: target variable\n- **5**: linear coefficient\n- **6**: constant product",
    category: 'Practice Problems',
    subcategory: 'Quadratic',
    type: 'solvable',
  },
  {
    id: 'quadratic_factor_gcf',
    slug: 'quadratic-factor-gcf',
    label: 'Factor out GCF',
    equation: '6 * x^2 + 9 * x = 0',
    description: "Quadratic without constant term solved by factoring out GCF.\n\n- **x**: target variable\n- **3*x**: greatest common factor",
    category: 'Practice Problems',
    subcategory: 'Quadratic',
    type: 'solvable',
  },
  {
    id: 'quadratic_factor_general',
    slug: 'quadratic-factor-general',
    label: 'Factor General Quadratic',
    equation: '2 * x^2 + 7 * x + 3 = 0',
    description: "Non-monic quadratic (a > 1) solvable by grouping/factoring.\n\n- **x**: target variable\n- **2**: leading coefficient a\n- **7, 3**: b and c coefficients",
    category: 'Practice Problems',
    subcategory: 'Quadratic',
    type: 'solvable',
  },
  {
    id: 'quadratic_constant_solve',
    slug: 'quadratic-constant-solve',
    label: 'Quadratic Formula Problem',
    equation: '3 * x^2 + 5 * x - 2 = 0',
    description: "General quadratic equation solved using the quadratic formula.\n\n- **x**: target variable\n- **3, 5, -2**: a, b, c coefficients",
    category: 'Practice Problems',
    subcategory: 'Quadratic',
    type: 'solvable',
  },
  {
    id: 'quadratic_radical',
    slug: 'quadratic-radical',
    label: 'Simple Radical',
    equation: 'sqrt(x) + 2 = 5',
    description: "Radical equation requiring isolation and squaring both sides.\n\n- **x**: target variable inside square root\n- **2, 5**: constants",
    category: 'Practice Problems',
    subcategory: 'Radicals',
    type: 'solvable',
  },
  {
    id: 'radical_linear',
    slug: 'radical-linear',
    label: 'Radical with Linear Expression',
    equation: 'sqrt(2 * x + 3) = 5',
    description: "Square root containing a linear expression.\n\n- **x**: target variable\n- **2*x + 3**: linear radicand",
    category: 'Practice Problems',
    subcategory: 'Radicals',
    type: 'solvable',
  },
  {
    id: 'radical_equal_roots',
    slug: 'radical-equal-roots',
    label: 'Equating Two Radicals',
    equation: 'sqrt(x + 5) = sqrt(2 * x - 1)',
    description: "Equation with square roots on both sides.\n\n- **x**: target variable",
    category: 'Practice Problems',
    subcategory: 'Radicals',
    type: 'solvable',
  },
  {
    id: 'radical_quadratic',
    slug: 'radical-quadratic',
    label: 'Radical Yielding Quadratic',
    equation: 'sqrt(x + 6) = x',
    description: "Radical equation that converts into a quadratic upon squaring.\n\n- **x**: target variable",
    category: 'Practice Problems',
    subcategory: 'Radicals',
    type: 'solvable',
  },
  {
    id: 'fraction_coefficients',
    slug: 'fraction-coefficients',
    label: 'Fractional Coefficients',
    equation: '(2 / 3) * x + 5 = 11',
    description: "Linear equation with fractional coefficient.\n\n- **x**: target variable\n- **2/3**: rational coefficient",
    category: 'Practice Problems',
    subcategory: 'Rationals',
    type: 'solvable',
  },
  {
    id: 'rational_basic',
    slug: 'rational-basic',
    label: 'Simple Rational Equation',
    equation: '6 / x = 3',
    description: "Equation with variable in denominator.\n\n- **x**: denominator variable (x ≠ 0)",
    category: 'Practice Problems',
    subcategory: 'Rationals',
    type: 'solvable',
  },
  {
    id: 'rational_proportion',
    slug: 'rational-proportion',
    label: 'Rational Proportion',
    equation: '2 / x = 5 / (x + 3)',
    description: "Proportion with binomial denominator.\n\n- **x**: variable in both denominators",
    category: 'Practice Problems',
    subcategory: 'Rationals',
    type: 'solvable',
  },
  {
    id: 'rational_sum',
    slug: 'rational-sum',
    label: 'Rational Sum with Variables',
    equation: '1 / x + 1 / (2 * x) = 3 / 4',
    description: "Sum of rational terms requiring common denominator.\n\n- **x**: variable denominator",
    category: 'Practice Problems',
    subcategory: 'Rationals',
    type: 'solvable',
  },
  {
    id: 'complex_basic',
    slug: 'complex-basic',
    label: 'Quadratic with Imaginary Roots',
    equation: 'x^2 + 4 = 0',
    description: "Pure quadratic yielding imaginary roots (x = ±2i).\n\n- **x**: target variable\n- **4**: positive constant",
    category: 'Practice Problems',
    subcategory: 'Complex',
    type: 'solvable',
    requiredSettings: {"allowComplex":true},
  },
  {
    id: 'complex_quadratic_formula',
    slug: 'complex-quadratic-formula',
    label: 'Complex Quadratic Formula',
    equation: 'x^2 - 2 * x + 5 = 0',
    description: "Quadratic equation with complex conjugate roots (1 ± 2i).\n\n- **x**: target variable",
    category: 'Practice Problems',
    subcategory: 'Complex',
    type: 'solvable',
    requiredSettings: {"allowComplex":true},
  },
  {
    id: 'complex_linear',
    slug: 'complex-linear',
    label: 'Complex Linear Equation',
    equation: '(2 + ⅈ) * x = 5',
    description: "Linear equation with complex coefficient.\n\n- **x**: target variable\n- **ⅈ**: imaginary unit",
    category: 'Practice Problems',
    subcategory: 'Complex',
    type: 'solvable',
    requiredSettings: {"allowComplex":true},
  },
  {
    id: 'exponent_basic',
    slug: 'exponent-basic',
    label: 'Simple Exponential Equation',
    equation: '2^x = 8',
    description: "Exponential equation with matching base.\n\n- **x**: exponent variable\n- **2**: base",
    category: 'Practice Problems',
    subcategory: 'Exponents & Logs',
    type: 'solvable',
  },
  {
    id: 'exponent_log_solve',
    slug: 'exponent-log-solve',
    label: 'Exponential Solvable by Logarithm',
    equation: '3^x = 7',
    description: "Exponential equation requiring logarithm.\n\n- **x**: exponent variable",
    category: 'Practice Problems',
    subcategory: 'Exponents & Logs',
    type: 'solvable',
  },
  {
    id: 'log_basic',
    slug: 'log-basic',
    label: 'Basic Logarithmic Equation',
    equation: 'log(x) + log(2) = log(10)',
    description: "Logarithmic equation requiring log product rule.\n\n- **x**: log argument",
    category: 'Practice Problems',
    subcategory: 'Exponents & Logs',
    type: 'solvable',
  },
  {
    id: 'literal_slope_intercept',
    slug: 'literal-slope-intercept',
    label: 'Slope-Intercept Form',
    equation: 'y = m * x + b',
    description: "Slope-intercept linear equation.\n\n- **y**: dependent variable\n- **m**: slope / rate of change\n- **x**: independent variable\n- **b**: y-intercept",
    category: 'Formulas & Laws',
    subcategory: 'Applied Math',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Linear_equation#Slope%E2%80%93intercept_form',
  },
  {
    id: 'literal_point_slope',
    slug: 'literal-point-slope',
    label: 'Point-Slope Form',
    equation: 'y - y_1 = m * (x - x_1)',
    description: "Point-slope linear equation.\n\n- **y, x**: general variables\n- **x_1, y_1**: given point coordinates\n- **m**: line slope",
    category: 'Formulas & Laws',
    subcategory: 'Applied Math',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Linear_equation#Point%E2%80%93slope_form',
  },
  {
    id: 'literal_distance_rate_time',
    slug: 'literal-distance-rate-time',
    label: 'Distance-Rate-Time Formula',
    equation: 'd = r * t',
    description: "Uniform motion relationship.\n\n- **d**: total distance\n- **r**: speed or travel rate\n- **t**: elapsed time",
    category: 'Formulas & Laws',
    subcategory: 'Applied Math',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Speed#Kinematics',
  },
  {
    id: 'literal_simple_interest',
    slug: 'literal-simple-interest',
    label: 'Simple Interest Formula',
    equation: 'I = P * r * t',
    description: "Financial simple interest accumulation.\n\n- **I**: interest earned or owed\n- **P**: principal balance\n- **r**: annual interest rate\n- **t**: time in years",
    category: 'Formulas & Laws',
    subcategory: 'Applied Math',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Interest#Simple_interest',
  },
  {
    id: 'literal_compound_interest',
    slug: 'literal-compound-interest',
    label: 'Compound Interest Formula',
    equation: 'A = P * (1 + r / n)^(n * t)',
    description: "Financial compound interest growth.\n\n- **A**: final balance amount\n- **P**: principal balance\n- **r**: annual interest rate\n- **n**: compounding periods per year\n- **t**: time in years",
    category: 'Formulas & Laws',
    subcategory: 'Applied Math',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Compound_interest',
  },
  {
    id: 'literal_temp_c_to_f',
    slug: 'literal-temp-c-to-f',
    label: 'Celsius to Fahrenheit',
    equation: 'F = (9 / 5) * C + 32',
    description: "Temperature scale conversion formula.\n\n- **F**: temperature in Fahrenheit\n- **C**: temperature in Celsius",
    category: 'Formulas & Laws',
    subcategory: 'Applied Math',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Fahrenheit#Conversion',
  },
  {
    id: 'literal_direct_variation',
    slug: 'literal-direct-variation',
    label: 'Direct Variation',
    equation: 'y = k * x',
    description: "Direct proportional relationship.\n\n- **y**: dependent quantity\n- **k**: constant of proportionality\n- **x**: independent quantity",
    category: 'Formulas & Laws',
    subcategory: 'Applied Math',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Proportionality_(mathematics)',
  },
  {
    id: 'literal_inverse_variation',
    slug: 'literal-inverse-variation',
    label: 'Inverse Variation',
    equation: 'y = k / x',
    description: "Inverse proportional relationship.\n\n- **y**: dependent quantity\n- **k**: variation constant\n- **x**: denominator quantity",
    category: 'Formulas & Laws',
    subcategory: 'Applied Math',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Inverse_proportionality',
  },
  {
    id: 'geom_pythagorean',
    slug: 'geom-pythagorean',
    label: 'Pythagorean Theorem',
    equation: 'a^2 + b^2 = c^2',
    description: "Right triangle side lengths relationship.\n\n- **a, b**: perpendicular leg lengths\n- **c**: hypotenuse length",
    category: 'Formulas & Laws',
    subcategory: 'Geometry',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Pythagorean_theorem',
  },
  {
    id: 'geom_distance_formula',
    slug: 'geom-distance-formula',
    label: 'Coordinate Distance Formula',
    equation: 'd = sqrt((x_2 - x_1)^2 + (y_2 - y_1)^2)',
    description: "Euclidean distance between Cartesian coordinates.\n\n- **d**: distance\n- **x_1, y_1**: first point coordinates\n- **x_2, y_2**: second point coordinates",
    category: 'Formulas & Laws',
    subcategory: 'Geometry',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Euclidean_distance',
  },
  {
    id: 'geom_midpoint',
    slug: 'geom-midpoint',
    label: 'Midpoint Formula',
    equation: 'm = (x_1 + x_2) / 2',
    description: "Midpoint along a coordinate axis.\n\n- **m**: midpoint coordinate value\n- **x_1, x_2**: endpoint coordinates",
    category: 'Formulas & Laws',
    subcategory: 'Geometry',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Midpoint',
  },
  {
    id: 'geom_rectangle_area',
    slug: 'geom-rectangle-area',
    label: 'Area of Rectangle',
    equation: 'A = w * h',
    description: "Surface area of a rectangle.\n\n- **A**: area\n- **w**: width\n- **h**: height",
    category: 'Formulas & Laws',
    subcategory: 'Geometry',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Rectangle',
  },
  {
    id: 'geom_triangle_area',
    slug: 'geom-triangle-area',
    label: 'Area of Triangle',
    equation: 'A = (1 / 2) * b * h',
    description: "Surface area of a 2D triangle.\n\n- **A**: area\n- **b**: base length\n- **h**: perpendicular height",
    category: 'Formulas & Laws',
    subcategory: 'Geometry',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Triangle#Computing_the_area_of_a_triangle',
  },
  {
    id: 'geom_circle_area',
    slug: 'geom-circle-area',
    label: 'Area of Circle',
    equation: 'A = pi * r^2',
    description: "Surface area of a circle.\n\n- **A**: area\n- **r**: radius\n- **pi**: mathematical constant pi",
    category: 'Formulas & Laws',
    subcategory: 'Geometry',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Area_of_a_circle',
  },
  {
    id: 'geom_circle_circumference',
    slug: 'geom-circle-circumference',
    label: 'Circumference of Circle',
    equation: 'C = 2 * pi * r',
    description: "Perimeter length of a circle.\n\n- **C**: circumference\n- **r**: radius\n- **pi**: mathematical constant pi",
    category: 'Formulas & Laws',
    subcategory: 'Geometry',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Circumference',
  },
  {
    id: 'geom_cylinder_volume',
    slug: 'geom-cylinder-volume',
    label: 'Volume of Cylinder',
    equation: 'V = pi * r^2 * h',
    description: "3D volume of a right circular cylinder.\n\n- **V**: volume\n- **r**: base radius\n- **h**: height",
    category: 'Formulas & Laws',
    subcategory: 'Geometry',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Cylinder#Volume',
  },
  {
    id: 'geom_cone_volume',
    slug: 'geom-cone-volume',
    label: 'Volume of Cone',
    equation: 'V = (1 / 3) * pi * r^2 * h',
    description: "3D volume of a right circular cone.\n\n- **V**: volume\n- **r**: base radius\n- **h**: height",
    category: 'Formulas & Laws',
    subcategory: 'Geometry',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Cone#Volume',
  },
  {
    id: 'geom_sphere_volume',
    slug: 'geom-sphere-volume',
    label: 'Volume of Sphere',
    equation: 'V = (4 / 3) * pi * r^3',
    description: "3D volume of a solid sphere.\n\n- **V**: volume\n- **r**: radius",
    category: 'Formulas & Laws',
    subcategory: 'Geometry',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Sphere#Enclosed_volume',
  },
  {
    id: 'physics_force',
    slug: 'physics-force',
    label: "Newton's Second Law",
    equation: 'F = m * a',
    description: "Newton's second law of motion.\n\n- **F**: net force vector\n- **m**: object mass\n- **a**: acceleration",
    category: 'Formulas & Laws',
    subcategory: 'Physics',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Newton%27s_laws_of_motion#Second_law',
  },
  {
    id: 'physics_gravity',
    slug: 'physics-gravity',
    label: 'Universal Gravitation',
    equation: 'F = G * (m_1 * m_2) / r^2',
    description: "Newton's law of universal gravitation.\n\n- **F**: gravitational force\n- **G**: gravitational constant\n- **m_1, m_2**: masses\n- **r**: separation distance",
    category: 'Formulas & Laws',
    subcategory: 'Physics',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Newton%27s_law_of_universal_gravitation',
  },
  {
    id: 'physics_mass_energy',
    slug: 'physics-mass-energy',
    label: 'Mass-Energy Equivalence',
    equation: 'E = m * c^2',
    description: "Einstein's mass-energy equivalence principle.\n\n- **E**: energy content\n- **m**: rest mass\n- **c**: speed of light constant",
    category: 'Formulas & Laws',
    subcategory: 'Physics',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Mass%E2%80%93energy_equivalence',
  },
  {
    id: 'physics_kinetic_energy',
    slug: 'physics-kinetic-energy',
    label: 'Kinetic Energy',
    equation: 'K = (1 / 2) * m * v^2',
    description: "Kinetic energy of a moving body.\n\n- **K**: kinetic energy\n- **m**: mass\n- **v**: velocity or speed",
    category: 'Formulas & Laws',
    subcategory: 'Physics',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Kinetic_energy',
  },
  {
    id: 'physics_potential_energy',
    slug: 'physics-potential-energy',
    label: 'Potential Energy',
    equation: 'U = m * g * h',
    description: "Gravitational potential energy near Earth.\n\n- **U**: potential energy\n- **m**: mass\n- **g**: gravitational acceleration\n- **h**: height",
    category: 'Formulas & Laws',
    subcategory: 'Physics',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Potential_energy',
  },
  {
    id: 'physics_kinematic_velocity',
    slug: 'physics-kinematic-velocity',
    label: 'Kinematic Final Velocity',
    equation: 'v = u + a * t',
    description: "Linear kinematic final velocity equation.\n\n- **v**: final velocity\n- **u**: initial velocity\n- **a**: acceleration\n- **t**: time duration",
    category: 'Formulas & Laws',
    subcategory: 'Physics',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Kinematics#Uniform_acceleration',
  },
  {
    id: 'physics_kinematic_displacement',
    slug: 'physics-kinematic-displacement',
    label: 'Kinematic Displacement',
    equation: 's = u * t + (1 / 2) * a * t^2',
    description: "Displacement under uniform acceleration.\n\n- **s**: displacement distance\n- **u**: initial velocity\n- **a**: acceleration\n- **t**: time",
    category: 'Formulas & Laws',
    subcategory: 'Physics',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Equations_of_motion',
  },
  {
    id: 'physics_wave',
    slug: 'physics-wave',
    label: 'Wave Speed Equation',
    equation: 'v = f * lambda',
    description: "Wave propagation speed equation.\n\n- **v**: wave speed\n- **f**: frequency in hertz\n- **lambda**: wavelength",
    category: 'Formulas & Laws',
    subcategory: 'Physics',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Wave#Wave_speed',
  },
  {
    id: 'physics_ohms_law',
    slug: 'physics-ohms-law',
    label: "Ohm's Law",
    equation: 'V = I * R',
    description: "Ohm's electrical circuit law.\n\n- **V**: voltage / potential difference\n- **I**: electric current\n- **R**: electrical resistance",
    category: 'Formulas & Laws',
    subcategory: 'Chem & Circuits',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Ohm%27s_law',
  },
  {
    id: 'physics_electric_power',
    slug: 'physics-electric-power',
    label: 'Electrical Power',
    equation: 'P = I * V',
    description: "Electric power dissipation equation.\n\n- **P**: power in watts\n- **I**: electric current\n- **V**: voltage",
    category: 'Formulas & Laws',
    subcategory: 'Chem & Circuits',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Electric_power',
  },
  {
    id: 'thermo_gas_law',
    slug: 'thermo-gas-law',
    label: 'Ideal Gas Law',
    equation: 'P * V = n * R * T',
    description: "Ideal gas law state equation.\n\n- **P**: pressure\n- **V**: volume\n- **n**: moles of gas\n- **R**: ideal gas constant\n- **T**: absolute temperature",
    category: 'Formulas & Laws',
    subcategory: 'Chem & Circuits',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Ideal_gas_law',
  },
  {
    id: 'thermo_density',
    slug: 'thermo-density',
    label: 'Density Formula',
    equation: 'rho = m / V',
    description: "Volumetric mass density formula.\n\n- **rho**: mass density\n- **m**: total mass\n- **V**: total volume",
    category: 'Formulas & Laws',
    subcategory: 'Chem & Circuits',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Density',
  },
  {
    id: 'thermo_boyles_law',
    slug: 'thermo-boyles-law',
    label: "Boyle's Gas Law",
    equation: 'P_1 * V_1 = P_2 * V_2',
    description: "Boyle's gas law at constant temperature.\n\n- **P_1, P_2**: initial and final pressures\n- **V_1, V_2**: initial and final volumes",
    category: 'Formulas & Laws',
    subcategory: 'Chem & Circuits',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Boyle%27s_law',
  },
  {
    id: 'thermo_specific_heat',
    slug: 'thermo-specific-heat',
    label: 'Thermal Heat Transfer',
    equation: 'Q = m * c * d',
    description: "Sensible heat transfer equation.\n\n- **Q**: thermal energy\n- **m**: mass\n- **c**: specific heat capacity\n- **d**: temperature change",
    category: 'Formulas & Laws',
    subcategory: 'Chem & Circuits',
    type: 'formula',
    wikiUrl: 'https://en.wikipedia.org/wiki/Heat_capacity#Specific_heat_capacity',
  },
  {
    id: 'quadratic_diff_of_squares',
    slug: 'quadratic-diff-of-squares',
    label: 'Difference of Squares',
    equation: 'x^2 - y^2 = (x - y) * (x + y)',
    description: "Fundamental difference of squares identity.\n\n- **x, y**: algebraic terms",
    category: 'Algebraic Identities',
    subcategory: 'Polynomials',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Difference_of_two_squares',
    tags: ['identity'],
  },
  {
    id: 'id_perfect_square_plus',
    slug: 'id-perfect-square-plus',
    label: 'Square of a Sum',
    equation: '(a + b)^2 = a^2 + 2 * a * b + b^2',
    description: "Expanded square of a sum identity.\n\n- **a, b**: polynomial terms",
    category: 'Algebraic Identities',
    subcategory: 'Polynomials',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Factorization#Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_perfect_square_minus',
    slug: 'id-perfect-square-minus',
    label: 'Square of a Difference',
    equation: '(a - b)^2 = a^2 - 2 * a * b + b^2',
    description: "Expanded square of a difference identity.\n\n- **a, b**: polynomial terms",
    category: 'Algebraic Identities',
    subcategory: 'Polynomials',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Factorization#Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_sum_cubes_factor',
    slug: 'id-sum-cubes-factor',
    label: 'Sum of Cubes Factoring',
    equation: 'a^3 + b^3 = (a + b) * (a^2 - a * b + b^2)',
    description: "Factored sum of cubes identity.\n\n- **a, b**: cubed terms",
    category: 'Algebraic Identities',
    subcategory: 'Polynomials',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Factorization#Sum/difference_of_two_cubes',
    tags: ['identity'],
  },
  {
    id: 'id_diff_cubes_factor',
    slug: 'id-diff-cubes-factor',
    label: 'Difference of Cubes Factoring',
    equation: 'a^3 - b^3 = (a - b) * (a^2 + a * b + b^2)',
    description: "Factored difference of cubes identity.\n\n- **a, b**: cubed terms",
    category: 'Algebraic Identities',
    subcategory: 'Polynomials',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Factorization#Sum/difference_of_two_cubes',
    tags: ['identity'],
  },
  {
    id: 'id_cube_sum_expand',
    slug: 'id-cube-sum-expand',
    label: 'Cube of a Sum',
    equation: '(a + b)^3 = a^3 + 3 * a^2 * b + 3 * a * b^2 + b^3',
    description: "Binomial expansion of a cubed sum.\n\n- **a, b**: binomial terms",
    category: 'Algebraic Identities',
    subcategory: 'Polynomials',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Binomial_theorem',
    tags: ['identity'],
  },
  {
    id: 'id_cube_diff_expand',
    slug: 'id-cube-diff-expand',
    label: 'Cube of a Difference',
    equation: '(a - b)^3 = a^3 - 3 * a^2 * b + 3 * a * b^2 - b^3',
    description: "Binomial expansion of a cubed difference.\n\n- **a, b**: binomial terms",
    category: 'Algebraic Identities',
    subcategory: 'Polynomials',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Binomial_theorem',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_product',
    slug: 'id-exponent-product',
    label: 'Product of Powers Rule',
    equation: 'x^2 * x^3 = 32',
    description: "Multiplying powers with equal bases.\n\n- **x**: base\n- **2, 3**: exponent powers",
    category: 'Algebraic Identities',
    subcategory: 'Exponents',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Exponentiation#Identities_and_properties',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_quotient',
    slug: 'id-exponent-quotient',
    label: 'Quotient of Powers Rule',
    equation: 'y^5 / y^2 = 8',
    description: "Dividing powers with equal bases.\n\n- **y**: base\n- **5, 2**: exponent powers",
    category: 'Algebraic Identities',
    subcategory: 'Exponents',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Exponentiation#Identities_and_properties',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_power_power',
    slug: 'id-exponent-power-power',
    label: 'Power of a Power Rule',
    equation: '(z^3)^2 = 64',
    description: "Raising an exponential expression to a power.\n\n- **z**: base\n- **3, 2**: exponent powers",
    category: 'Algebraic Identities',
    subcategory: 'Exponents',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Exponentiation#Identities_and_properties',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_power_product',
    slug: 'id-exponent-power-product',
    label: 'Power of a Product Rule',
    equation: '(a * b)^3 = 27',
    description: "Distributing a power across a product.\n\n- **a, b**: base factors\n- **3**: exponent power",
    category: 'Algebraic Identities',
    subcategory: 'Exponents',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Exponentiation#Identities_and_properties',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_negative',
    slug: 'id-exponent-negative',
    label: 'Negative Exponent Definition',
    equation: 'x^-3 = 1 / 8',
    description: "Converting negative exponents to reciprocal powers.\n\n- **x**: base (x ≠ 0)\n- **-3**: negative exponent power",
    category: 'Algebraic Identities',
    subcategory: 'Exponents',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Exponentiation#Negative_exponents',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_sqrt_reverse',
    slug: 'id-exponent-sqrt-reverse',
    label: 'Fractional Power to Square Root',
    equation: 'x^(1 / 2) = 4',
    description: "Convert a fractional exponent of 1/2 back to a square root.\n\n- **x**: base\n- **1/2**: fractional exponent",
    category: 'Algebraic Identities',
    subcategory: 'Exponents',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Exponentiation#Rational_exponents',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_sqrt',
    slug: 'id-exponent-sqrt',
    label: 'Fractional Exponent Rule',
    equation: 'sqrt(x) = 5',
    description: "Equivalence between square root and power 1/2.\n\n- **x**: non-negative radicand",
    category: 'Algebraic Identities',
    subcategory: 'Exponents',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Exponentiation#Rational_exponents',
    tags: ['identity'],
  },
  {
    id: 'id_log_product',
    slug: 'id-log-product',
    label: 'Logarithm Product Rule',
    equation: 'log(x * y) = 5',
    description: "Logarithm of a product as a sum of logarithms.\n\n- **x, y**: positive logarithmic arguments",
    category: 'Algebraic Identities',
    subcategory: 'Logarithms',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Logarithm#Logarithmic_identities',
    tags: ['identity'],
  },
  {
    id: 'id_log_quotient',
    slug: 'id-log-quotient',
    label: 'Logarithm Quotient Rule',
    equation: 'log(a / b) = 3',
    description: "Logarithm of a quotient as a difference of logarithms.\n\n- **a, b**: positive logarithmic arguments",
    category: 'Algebraic Identities',
    subcategory: 'Logarithms',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Logarithm#Logarithmic_identities',
    tags: ['identity'],
  },
  {
    id: 'id_log_power',
    slug: 'id-log-power',
    label: 'Logarithm Power Rule',
    equation: 'log(x^3) = 9',
    description: "Bringing down an exponent in a logarithm.\n\n- **x**: positive base argument\n- **3**: exponent power",
    category: 'Algebraic Identities',
    subcategory: 'Logarithms',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Logarithm#Logarithmic_identities',
    tags: ['identity'],
  },
  {
    id: 'id_log_change_base',
    slug: 'id-log-change-base',
    label: 'Change of Base Formula',
    equation: 'log(x, 10) = 2',
    description: "Converting logarithms between arbitrary bases.\n\n- **x**: argument\n- **10**: base",
    category: 'Algebraic Identities',
    subcategory: 'Logarithms',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Logarithm#Change_of_base',
    tags: ['identity'],
  },
  {
    id: 'id_trig_pythagorean',
    slug: 'id-trig-pythagorean',
    label: 'Pythagorean Trig Identity',
    equation: 'sin(phi)^2 + cos(phi)^2 = 1',
    description: "Fundamental trigonometric Pythagorean identity.\n\n- **phi**: angle argument",
    category: 'Algebraic Identities',
    subcategory: 'Trigonometry',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Pythagorean_trigonometric_identity',
    tags: ['identity'],
  },
  {
    id: 'id_trig_tan_def',
    slug: 'id-trig-tan-def',
    label: 'Tangent Quotient Identity',
    equation: 'tan(x) = y',
    description: "Quotient definition of tangent function.\n\n- **x**: angle argument\n- **y**: tangent value",
    category: 'Algebraic Identities',
    subcategory: 'Trigonometry',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/List_of_trigonometric_identities',
    tags: ['identity'],
  },
  {
    id: 'id_trig_cot_def',
    slug: 'id-trig-cot-def',
    label: 'Cotangent Quotient Identity',
    equation: 'cot(x) = 2',
    description: "Quotient definition of cotangent function.\n\n- **x**: angle argument",
    category: 'Algebraic Identities',
    subcategory: 'Trigonometry',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/List_of_trigonometric_identities',
    tags: ['identity'],
  },
  {
    id: 'id_trig_sec_def',
    slug: 'id-trig-sec-def',
    label: 'Secant Reciprocal Identity',
    equation: 'sec(t) = 2',
    description: "Reciprocal definition of secant function.\n\n- **t**: angle argument",
    category: 'Algebraic Identities',
    subcategory: 'Trigonometry',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/List_of_trigonometric_identities',
    tags: ['identity'],
  },
  {
    id: 'id_trig_csc_def',
    slug: 'id-trig-csc-def',
    label: 'Cosecant Reciprocal Identity',
    equation: 'csc(u) = v',
    description: "Reciprocal definition of cosecant function.\n\n- **u**: angle argument",
    category: 'Algebraic Identities',
    subcategory: 'Trigonometry',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/List_of_trigonometric_identities',
    tags: ['identity'],
  },
  {
    id: 'id_trig_pythagorean_tan_sec',
    slug: 'id-trig-pythagorean-tan-sec',
    label: 'Tangent-Secant Identity',
    equation: 'tan(theta)^2 + 1 = y',
    description: "Secondary Pythagorean identity relating tangent and secant.\n\n- **theta**: angle argument",
    category: 'Algebraic Identities',
    subcategory: 'Trigonometry',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Pythagorean_trigonometric_identity',
    tags: ['identity'],
  },
  {
    id: 'id_trig_pythagorean_cot_csc',
    slug: 'id-trig-pythagorean-cot-csc',
    label: 'Cotangent-Cosecant Identity',
    equation: '1 + cot(theta)^2 = z',
    description: "Secondary Pythagorean identity relating cotangent and cosecant.\n\n- **theta**: angle argument",
    category: 'Algebraic Identities',
    subcategory: 'Trigonometry',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Pythagorean_trigonometric_identity',
    tags: ['identity'],
  },
  {
    id: 'id_trig_double_sin',
    slug: 'id-trig-double-sin',
    label: 'Double Angle Sine',
    equation: 'sin(2 * theta) = 1',
    description: "Double-angle sine expansion identity.\n\n- **theta**: angle argument",
    category: 'Algebraic Identities',
    subcategory: 'Trigonometry',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/List_of_trigonometric_identities#Double-angle_formulae',
    tags: ['identity'],
  },
  {
    id: 'id_trig_double_cos',
    slug: 'id-trig-double-cos',
    label: 'Double Angle Cosine',
    equation: 'cos(2 * x) = y',
    description: "Double-angle cosine expansion identity.\n\n- **x**: angle argument",
    category: 'Algebraic Identities',
    subcategory: 'Trigonometry',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/List_of_trigonometric_identities#Double-angle_formulae',
    tags: ['identity'],
  },
  {
    id: 'id_complex_definition',
    slug: 'id-complex-definition',
    label: 'Imaginary Unit Definition',
    equation: 'ⅈ^2 = -1',
    description: "Fundamental identity defining the imaginary unit.\n\n- **ⅈ**: imaginary unit (i = sqrt(-1))",
    category: 'Algebraic Identities',
    subcategory: 'Complex',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Imaginary_unit',
    requiredSettings: {"allowComplex":true},
  },
  {
    id: 'id_complex_conjugate',
    slug: 'id-complex-conjugate',
    label: 'Complex Conjugate Multiplication',
    equation: '(a + b * ⅈ) * (a - b * ⅈ) = a^2 + b^2',
    description: "Product of complex conjugates resulting in a real number.\n\n- **a**: real component\n- **b**: imaginary coefficient",
    category: 'Algebraic Identities',
    subcategory: 'Complex',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Complex_conjugate',
    requiredSettings: {"allowComplex":true},
  },
  {
    id: 'id_complex_rationalization',
    slug: 'id-complex-rationalization',
    label: 'Complex Denominator Rationalization',
    equation: '1 / (a + b * ⅈ) = (a - b * ⅈ) / (a^2 + b^2)',
    description: "Reciprocal of a complex number resolved via conjugate multiplication.\n\n- **a**: real part\n- **b**: imaginary coefficient",
    category: 'Algebraic Identities',
    subcategory: 'Complex',
    type: 'identity',
    wikiUrl: 'https://en.wikipedia.org/wiki/Complex_number#Reciprocal_and_division',
    requiredSettings: {"allowComplex":true},
  },
];

/**
 * One representative example equation per library category (#245), shown in the
 * category header's hover tooltip so users get a preview of what a section holds
 * — and osmotic guidance on the input syntax (explicit `*`, `^`, `sqrt(...)`).
 * Kept as the raw input string on purpose: it teaches what to type. Coverage of
 * every {@link PRESET_LIST} category is guarded by categoryExamples.test.ts.
 */
export const CATEGORY_EXAMPLES: Record<string, string> = {
  'Practice Problems': '2 * x + 4 = 10',
  'Formulas & Laws': 'E = m * c^2',
  'Algebraic Identities': 'sin(phi)^2 + cos(phi)^2 = 1',
};
