// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Robert Harris

export interface Preset {
  id: string;
  label: string;
  equation: string;
  description: string;
  category: string;
  // Pedagogical tags, independent of display category. `identity` marks presets
  // that demonstrate an algebraic-identity rewrite (validated in
  // math-engine/tests/presets.test.ts).
  tags?: string[];
}

export const PRESET_LIST: Preset[] = [
  // ─────────────────────────────────────────────────────────────
  // Linear & Basic Algebra
  // ─────────────────────────────────────────────────────────────
  {
    id: 'linear_basic',
    label: 'Basic Linear Equation',
    equation: '2 * x + 4 = 10',
    description: 'Solve for x in a standard two-step linear equation.',
    category: 'Linear & Basic Algebra',
  },
  {
    id: 'linear_both_sides',
    label: 'Variables on Both Sides',
    equation: '3 * x + 5 = x + 13',
    description: 'Collect variables on one side and constants on the other.',
    category: 'Linear & Basic Algebra',
  },
  {
    id: 'linear_negative',
    label: 'Negative Coefficients',
    equation: '-2 * x + 7 = 15',
    description: 'Practice transposing with negative multiplier coefficients.',
    category: 'Linear & Basic Algebra',
  },
  {
    id: 'linear_distribution',
    label: 'Distribution Form',
    equation: '3 * (x - 2) = 18',
    description: 'Distribute the multiplication across brackets or divide both sides.',
    category: 'Linear & Basic Algebra',
  },
  {
    id: 'linear_multi_step',
    label: 'Multi-Step Linear',
    equation: '5 * x - 3 + 2 * x = 4 * x + 9',
    description: 'Group like terms first to simplify the transposition process.',
    category: 'Linear & Basic Algebra',
  },

  // ─────────────────────────────────────────────────────────────
  // Quadratics & Polynomials
  // ─────────────────────────────────────────────────────────────
  {
    id: 'quadratic_general',
    label: 'General Quadratic Equation',
    equation: 'a * x^2 + b * x + c = 0',
    description: 'Standard form of a quadratic equation. Practice operations to complete the square.',
    category: 'Quadratics & Polynomials',
  },
  {
    id: 'quadratic_formula_pos',
    label: 'Quadratic Formula, Positive Branch',
    equation: 'x = (-b + sqrt(b^2 - 4 * a * c)) / (2 * a)',
    description: 'Solve for x using the positive branch of the quadratic formula.',
    category: 'Quadratics & Polynomials',
  },
  {
    id: 'quadratic_formula_neg',
    label: 'Quadratic Formula, Negative Branch',
    equation: 'x = (-b - sqrt(b^2 - 4 * a * c)) / (2 * a)',
    description: 'Solve for x using the negative branch of the quadratic formula.',
    category: 'Quadratics & Polynomials',
  },
  {
    id: 'quadratic_constant_solve',
    label: 'Solvable Quadratic with Constants',
    equation: '3 * x^2 + 5 * x - 2 = 0',
    description: 'A quadratic equation with constant coefficients. Drag x to the RHS to apply the quadratic formula solver.',
    category: 'Quadratics & Polynomials',
  },
  {
    id: 'quadratic_basic_solve',
    label: 'Quadratic Equation',
    equation: 'x^2 - 4 = 0',
    description: 'Practice taking square roots or factoring difference of squares.',
    category: 'Quadratics & Polynomials',
  },
  {
    id: 'quadratic_factored',
    label: 'Factored Quadratic',
    equation: '(x + 2) * (x + 3) = 0',
    description: 'Utilize the zero-product property to find solutions.',
    category: 'Quadratics & Polynomials',
  },
  {
    id: 'quadratic_factor_monic',
    label: 'Factor Monic Quadratic',
    equation: 'x^2 + 5 * x + 6 = 0',
    description: 'Factor a trinomial quadratic expression into two binomials.',
    category: 'Quadratics & Polynomials',
  },
  {
    id: 'quadratic_factor_gcf',
    label: 'Factor out GCF',
    equation: '6 * x^2 + 9 * x = 0',
    description: 'Extract the greatest common factor (GCF) from the terms.',
    category: 'Quadratics & Polynomials',
  },
  {
    id: 'quadratic_factor_general',
    label: 'Factor General Quadratic',
    equation: '2 * x^2 + 7 * x + 3 = 0',
    description: 'Factor a quadratic expression with a leading coefficient greater than 1.',
    category: 'Quadratics & Polynomials',
  },
  {
    id: 'quadratic_diff_of_squares',
    label: 'Difference of Squares',
    equation: 'x^2 - y^2 = (x - y) * (x + y)',
    description: 'Classical algebraic identity for factoring quadratic polynomials.',
    category: 'Quadratics & Polynomials',
  },
  {
    id: 'id_diff_squares_factor_constant',
    label: 'Constant Difference of Squares',
    equation: 'x^2 - 9 = y',
    description: 'Factor x^2 - 9 by recognizing 9 as a perfect square (3^2).',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_diff_squares_expand',
    label: 'Expand a Difference of Squares',
    equation: '(x - 4) * (x + 4) = 9',
    description: 'Expand conjugate binomial factors back to difference of squares.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_perfect_square_plus',
    label: 'Factor a Perfect-Square Sum',
    equation: 'a^2 + 2 * a * 3 + 3^2 = 25',
    description: 'Factor a quadratic trinomial of the form a^2 + 2ab + b^2.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_perfect_square_minus',
    label: 'Factor a Perfect-Square Difference',
    equation: 'b^2 - 2 * b * 5 + 5^2 = 16',
    description: 'Factor a quadratic trinomial of the form b^2 - 2ab + b^2.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_perfect_square_expand_plus',
    label: 'Expand a Squared Sum',
    equation: '(y + 2)^2 = z',
    description: 'Expand a binomial squared sum into trinomial form.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_perfect_square_expand_minus',
    label: 'Expand a Squared Difference',
    equation: '(z - 3)^2 = 10',
    description: 'Expand a binomial squared difference into trinomial form.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_sum_cubes_factor',
    label: 'Factor a Sum of Cubes',
    equation: 'x^3 + 2^3 = y',
    description: 'Factor a sum of cubes x^3 + 2^3 using polynomial identity.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_diff_cubes_factor',
    label: 'Factor a Difference of Cubes',
    equation: 'x^3 - y^3 = 7',
    description: 'Factor a difference of cubes x^3 - y^3 using polynomial identity.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_cube_sum_factor',
    label: 'Factor a Perfect-Cube Sum',
    equation: 'x^3 + 3 * x^2 * 2 + 3 * x * 2^2 + 2^3 = y',
    description: 'Factor x^3 + 6x^2 + 12x + 8 into a cubed sum (x + 2)^3.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_cube_sum_expand',
    label: 'Expand a Cubed Sum',
    equation: '(a + 3)^3 = b',
    description: 'Expand a binomial cubed sum (a + 3)^3 into polynomial form.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_cube_diff_factor',
    label: 'Factor a Perfect-Cube Difference',
    equation: 'x^3 - 3 * x^2 * 4 + 3 * x * 4^2 - 4^3 = y',
    description: 'Factor x^3 - 12x^2 + 48x - 64 into a cubed difference (x - 4)^3.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_cube_diff_expand',
    label: 'Expand a Cubed Difference',
    equation: '(b - 2)^3 = c',
    description: 'Expand a binomial cubed difference (b - 2)^3 into polynomial form.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_product',
    label: 'Product of Powers',
    equation: 'x^2 * x^3 = 32',
    description: 'Combine multiplication of powers with the same base x.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_quotient',
    label: 'Quotient of Powers',
    equation: 'y^5 / y^2 = 8',
    description: 'Simplify division of powers with the same base y.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_power_power',
    label: 'Power of a Power',
    equation: '(z^3)^2 = 64',
    description: 'Simplify a power raised to another exponent.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_power_product',
    label: 'Power of a Product',
    equation: '(a * b)^3 = 27',
    description: 'Distribute power exponent over a product term.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_negative',
    label: 'Negative Exponent Rule',
    equation: 'x^-3 = 1 / 8',
    description: 'Express negative powers as reciprocals.',
    category: 'Quadratics & Polynomials',
    tags: ['identity'],
  },

  // ─────────────────────────────────────────────────────────────
  // Fractions, Radicals & Rationals
  // ─────────────────────────────────────────────────────────────
  {
    id: 'fraction_linear',
    label: 'Linear with Fractions',
    equation: '(x + 4) / 2 = y - 1',
    description: 'Clear denominators by multiplying both sides of the equation.',
    category: 'Fractions, Radicals & Rationals',
  },
  {
    id: 'fraction_proportion',
    label: 'Basic Proportion',
    equation: 'a / b = c / d',
    description: 'Standard ratio equivalence. Practice cross-multiplication transpositions.',
    category: 'Fractions, Radicals & Rationals',
  },
  {
    id: 'fraction_direct_variation',
    label: 'Direct Variation Ratio',
    equation: 'y / x = k',
    description: 'Represents a constant ratio relationship between y and x.',
    category: 'Fractions, Radicals & Rationals',
  },
  {
    id: 'fraction_average',
    label: 'Three-Value Average',
    equation: 'A = (x + y + z) / 3',
    description: 'The arithmetic mean of three values x, y, and z.',
    category: 'Fractions, Radicals & Rationals',
  },
  {
    id: 'fraction_coefficients',
    label: 'Fractional Coefficients',
    equation: '(2 / 3) * x + 5 = 11',
    description: 'Linear equation containing non-integer variable multipliers.',
    category: 'Fractions, Radicals & Rationals',
  },
  {
    id: 'quadratic_radical',
    label: 'Simple Radical',
    equation: 'sqrt(x) + 2 = 5',
    description: 'Isolate the square root term then raise both sides to power 2.',
    category: 'Fractions, Radicals & Rationals',
  },
  {
    id: 'id_exponent_sqrt',
    label: 'Square Root to Exponent',
    equation: 'sqrt(x) = 5',
    description: 'Convert a square root term into a fractional exponent of 1/2.',
    category: 'Fractions, Radicals & Rationals',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_sqrt_reverse',
    label: 'Fractional Power to Sqrt',
    equation: 'x^(1 / 2) = 4',
    description: 'Convert an exponent of 1/2 back to a square root.',
    category: 'Fractions, Radicals & Rationals',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_nthRoot',
    label: 'Nth Root to Exponent',
    equation: 'nthRoot(y, 3) = 2',
    description: 'Convert a cube/nth root term into a fractional exponent 1/n.',
    category: 'Fractions, Radicals & Rationals',
    tags: ['identity'],
  },
  {
    id: 'id_exponent_nthRoot_reverse',
    label: 'Fractional Power to Nth Root',
    equation: 'y^(1 / 3) = 3',
    description: 'Convert a fractional exponent 1/n back to an nth root.',
    category: 'Fractions, Radicals & Rationals',
    tags: ['identity'],
  },

  // ─────────────────────────────────────────────────────────────
  // Transcendental (Logs & Trig)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'id_log_product',
    label: 'Logarithm Product Rule',
    equation: 'log(x * y) = 5',
    description: 'Expand logarithm of product into a sum of logarithms.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_log_quotient',
    label: 'Logarithm Quotient Rule',
    equation: 'log(a / b) = 3',
    description: 'Expand logarithm of quotient into a difference of logarithms.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_log_power',
    label: 'Logarithm Power Rule',
    equation: 'log(x^3) = 9',
    description: 'Move log argument power exponent to multiplier coefficient.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_log_change_base',
    label: 'Logarithm Change of Base',
    equation: 'log(x, 10) = 2',
    description: 'Expand a base-10 logarithm into a quotient of natural logarithms.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_log_change_base_reverse',
    label: 'Reverse Log Change of Base',
    equation: 'log(x) / log(3) = 4',
    description: 'Condenses a quotient of natural logarithms into a log with custom base.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_pythagorean',
    label: 'Pythagorean Trig Identity',
    equation: 'sin(phi)^2 + cos(phi)^2 = 1',
    description: 'Simplify sin^2 + cos^2 of any angle to 1.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_tan_def',
    label: 'Tangent Quotient Identity',
    equation: 'tan(x) = y',
    description: 'Express tangent function as sine over cosine.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_sec_def',
    label: 'Secant Reciprocal Identity',
    equation: 'sec(t) = 2',
    description: 'Express secant function as reciprocal of cosine.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_csc_def',
    label: 'Cosecant Reciprocal Identity',
    equation: 'csc(u) = v',
    description: 'Express cosecant function as reciprocal of sine.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_double_sin',
    label: 'Double Angle Sine',
    equation: 'sin(2 * theta) = 1',
    description: 'Expand sine of a double angle.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_cot_def',
    label: 'Cotangent Quotient Identity',
    equation: 'cot(x) = 2',
    description: 'Express cotangent as cosine over sine.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_cot_reciprocal',
    label: 'Cotangent Reciprocal',
    equation: 'cot(theta) = y',
    description: 'Express cotangent as the reciprocal of tangent.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_tan_reciprocal',
    label: 'Tangent Reciprocal',
    equation: 'tan(theta) = 1 / z',
    description: 'Express tangent as the reciprocal of cotangent.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_pythagorean_cos_sq',
    label: 'Pythagorean Identity for cos^2',
    equation: '1 - sin(x)^2 = y',
    description: 'Rewrite 1 - sin^2(x) using cosine squared.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_pythagorean_sin_sq',
    label: 'Pythagorean Identity for sin^2',
    equation: '1 - cos(x)^2 = z',
    description: 'Rewrite 1 - cos^2(x) using sine squared.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_pythagorean_tan_sec',
    label: 'Tangent-Secant Pythagorean Identity',
    equation: 'tan(theta)^2 + 1 = y',
    description: 'Rewrite tan^2(theta) + 1 using secant squared.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_pythagorean_cot_csc',
    label: 'Cotangent-Cosecant Pythagorean Identity',
    equation: '1 + cot(theta)^2 = z',
    description: 'Rewrite 1 + cot^2(theta) using cosecant squared.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_double_cos_form1',
    label: 'Cosine Double Angle as cos^2 - sin^2',
    equation: 'cos(2 * x) = y',
    description: 'Expand double angle cosine using difference of squares.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_double_cos_form2',
    label: 'Cosine Double Angle as 2cos^2 - 1',
    equation: 'cos(2 * theta) = z',
    description: 'Expand double angle cosine using cosine only.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_double_cos_form3',
    label: 'Cosine Double Angle as 1 - 2sin^2',
    equation: 'cos(2 * phi) = w',
    description: 'Expand double angle cosine using sine only.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },
  {
    id: 'id_trig_double_tan',
    label: 'Double Angle Tangent',
    equation: 'tan(2 * x) = y',
    description: 'Expand tangent of a double angle.',
    category: 'Transcendental (Logs & Trig)',
    tags: ['identity'],
  },

  // ─────────────────────────────────────────────────────────────
  // Formulas (Physics, Geometry & Science)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'literal_slope_intercept',
    label: 'Slope-Intercept Formula',
    equation: 'y = m * x + b',
    description: 'A straight line giving output y for input x, with slope m and y-intercept b.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'literal_rectangle_area',
    label: 'Rectangle Area',
    equation: 'A = w * h',
    description: 'Area A of a rectangle with width w and height h.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'literal_rectangle_perimeter',
    label: 'Rectangle Perimeter',
    equation: 'P = 2 * l + 2 * w',
    description: 'Perimeter P around a rectangle of length l and width w.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'literal_simple_interest',
    label: 'Simple Interest',
    equation: 'I = P * r * t',
    description: 'Interest I earned on principal P at rate r over time t.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'literal_temp_c_to_f',
    label: 'Celsius to Fahrenheit',
    equation: 'F = (9 / 5) * C + 32',
    description: 'Temperature in Fahrenheit F converted from a Celsius temperature C.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'geom_pythagorean',
    label: 'Pythagorean Theorem',
    equation: 'a^2 + b^2 = c^2',
    description: 'Relation between legs a, b and hypotenuse c in a right-angled triangle.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'geom_circle_area',
    label: 'Area of Circle',
    equation: 'A = pi * r^2',
    description: 'Area A of a circle of radius r, where pi is the ratio of circumference to diameter.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'geom_cylinder_volume',
    label: 'Volume of Cylinder',
    equation: 'V = pi * r^2 * h',
    description: 'Calculates volume V given base radius r and height h.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'geom_sphere_volume',
    label: 'Volume of Sphere',
    equation: 'V = (4 / 3) * pi * r^3',
    description: 'Volume V of a sphere of radius r.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'quadratic_circle',
    label: 'Circle Equation',
    equation: 'x^2 + y^2 = r^2',
    description: 'A circle centered at the origin: every point with coordinates x and y sits at radius r.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'physics_force',
    label: "Newton's Second Law",
    equation: 'F = m * a',
    description: 'Force F equals mass m times acceleration a.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'physics_mass_energy',
    label: 'Mass-Energy Equivalence',
    equation: 'E = m * c^2',
    description: 'Energy E equals mass m times the speed of light c squared.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'physics_kinetic_energy',
    label: 'Kinetic Energy',
    equation: 'K = (1 / 2) * m * v^2',
    description: 'Kinetic energy K of a body of mass m moving at velocity v.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'physics_acceleration',
    label: 'Constant Acceleration',
    equation: 'v = u + a * t',
    description: 'Final velocity v given initial velocity u, acceleration a, and time t.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'physics_ohms_law',
    label: "Ohm's Law",
    equation: 'V = I * R',
    description: 'Voltage V equals current I multiplied by electrical resistance R.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'physics_wave',
    label: 'Wave Speed Equation',
    equation: 'v = f * lambda',
    description: 'Wave velocity v as frequency f multiplied by wavelength λ.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'thermo_gas_law',
    label: 'Ideal Gas Law',
    equation: 'P * V = n * R * T',
    description: 'Pressure P times volume V equals amount n times the gas constant R times temperature T.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'thermo_density',
    label: 'Density Formula',
    equation: 'rho = m / V',
    description: 'Density ρ of a substance equal to its mass m divided by volume V.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'thermo_boyles_law',
    label: "Boyle's Law",
    equation: 'P_1 * V_1 = P_2 * V_2',
    description: 'A gas at constant temperature: initial pressure P_1 and volume V_1 give the same product as final pressure P_2 and volume V_2.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
  {
    id: 'thermo_specific_heat',
    label: 'Specific Heat Energy',
    equation: 'Q = m * c * d',
    description: 'Heat energy absorbed Q given mass m, specific heat c, and temp delta d.',
    category: 'Formulas (Physics, Geometry & Science)',
  },
];
